module(name = "app", version = "1.0.0")

bazel_dep(name = "rules_java", version = "9.9.0")
bazel_dep(name = "rules_jvm_external", version = "7.1")

maven = use_extension("@rules_jvm_external//:extensions.bzl", "maven")
maven.install(
    artifacts = [
        "org.apache.avro:avro:1.12.2",
        "org.apache.avro:avro-tools:1.12.2",
    ],
    excluded_artifacts = ["org.slf4j:slf4j-log4j12"],
    repositories = ["https://repo1.maven.org/maven2"],
)
use_repo(maven, "maven")
