module(name = "app", version = "1.0.0")

bazel_dep(name = "rules_java", version = "9.9.0")
bazel_dep(name = "rules_jvm_external", version = "7.1")
bazel_dep(name = "package_metadata", version = "0.0.13")
bazel_dep(name = "supply_chain_tools", version = "0.0.3")
bazel_dep(name = "supply-chain-go", version = "0.0.11")
bazel_dep(name = "rules_go", version = "0.60.0")

git_override(
    module_name = "supply_chain_tools",
    commit = "75e58c0f8da5217b66b19dfa2bf2176668eb84f4",
    remote = "https://github.com/bazel-contrib/supply-chain.git",
    strip_prefix = "tools",
)

git_override(
    module_name = "supply-chain-go",
    commit = "b765e5714bd82e1c6aa4aed8530afd1bcddd0aea",
    remote = "https://github.com/bazel-contrib/supply-chain.git",
    strip_prefix = "lib/supplychain-go",
)

go_sdk = use_extension("@rules_go//go:extensions.bzl", "go_sdk")
go_sdk.download(version = "1.26.8")

maven = use_extension("@rules_jvm_external//:extensions.bzl", "maven")
maven.install(
    artifacts = [
        "org.slf4j:slf4j-api:2.0.20",
        "com.fasterxml.jackson.core:jackson-databind:2.22.3",
        "info.picocli:picocli:4.7.7",
        "org.jspecify:jspecify:1.0.1",
    ],
    repositories = ["https://repo1.maven.org/maven2"],
)
use_repo(maven, "maven")
