module(name = "app", version = "1.0.0")

bazel_dep(name = "rules_java", version = "9.9.0")
bazel_dep(name = "rules_kotlin", version = "2.4.20")
bazel_dep(name = "rules_jvm_external", version = "7.1")

maven = use_extension("@rules_jvm_external//:extensions.bzl", "maven")
maven.install(
    artifacts = [
        "org.jetbrains.kotlinx:kotlinx-serialization-json-jvm:1.11.0",
    ],
    repositories = ["https://repo1.maven.org/maven2"],
)
use_repo(maven, "maven")

register_toolchains("//:kotlin_toolchain")
