load("@rules_java//java:java_binary.bzl", "java_binary")
load("@rules_java//toolchains:default_java_toolchain.bzl", "default_java_toolchain")

java_binary(
    name = "hello",
    srcs = glob(["src/main/java/**/*.java"]),
    main_class = "demo.hello.Main",
)

default_java_toolchain(
    name = "local_toolchain",
    java_runtime = "@rules_java//toolchains:current_host_java_runtime",
    source_version = "25",
    target_version = "25",
)
