module(name = "app", version = "1.0.0")

bazel_dep(name = "rules_java", version = "9.9.0")
bazel_dep(name = "rules_jvm_external", version = "7.1")
bazel_dep(name = "rules_oci", version = "2.3.0")
bazel_dep(name = "rules_pkg", version = "1.3.0")

maven = use_extension("@rules_jvm_external//:extensions.bzl", "maven")
maven.install(
    artifacts = [
        "org.slf4j:slf4j-api:2.0.20",
        "com.fasterxml.jackson.core:jackson-databind:2.22.3",
        "info.picocli:picocli:4.7.7",
        "org.jspecify:jspecify:1.0.1",
    ],
    repositories = ["https://repo1.maven.org/maven2"],
)
use_repo(maven, "maven")

oci = use_extension("@rules_oci//oci:extensions.bzl", "oci")
oci.pull(
    name = "temurin",
    image = "docker.io/library/eclipse-temurin",
    digest = "sha256:8da0490fa9a3c26867012019565948eef0ee69438f5c75ac28146967bae984b5",  # 25-jre
    platforms = ["linux/amd64"],
)
use_repo(oci, "temurin", "temurin_linux_amd64")
